### ISSUE TITLE
[PlayerList] Add avatar sdk version to list

### ISSUE THREAD

**Issue by Bluscream** [loukylor/VRC-Mods#35]

**Comment by loukylor** [comment]
I don't quite get why you'd want this. And you can already tell by just looking in expressions.

**Comment by Bluscream** [comment]
I want to see it for other pkayers avatars, hence the "add to list"

**Comment by loukylor** [comment]
I don't really think this would be super useful information, and it would just add to the size of the list. If need be you can just ask people.

**Comment by Bluscream** [comment]
Aslong as its optional, i dont see it being a big problem, also as a world creator its nice since there are a few collider related bugs with sdk2 avis on sdk3 worlds so you can suggest people to switch to a sdk3 avi to avoid those

**Comment by loukylor** [comment]
But again, you can just ask them. 
"Hey are you using an sdk 3 avatar?"
"No"
"Then switch to one, it'll do something or other"

**Comment by Bluscream** [comment]
Well, you could say the same for a lot of infos in PL (some things are even twice on the same menu), its just convinient to have it there.

**Comment by loukylor** [comment]
The reason most of the info is there is because either a large number of people wanted it or because they gave a valid reason that would be time consuming to figure out. For example, the avatar performance information is there to keep people from using too poor performance of an avatar during events. It solves an issue that would be hugely time consuming otherwise. 

Is your issue hugely time consuming or are there a lot of people asking for it?
